export const GAME = {
  SCREEN_PADDING: 20,

  SHIP_WIDTH: 40,
  SHIP_HEIGHT: 52,

  ASTEROID_MIN_SIZE: 30,
  ASTEROID_MAX_SIZE: 60,

  ASTEROID_MIN_SPEED: 3,
  ASTEROID_MAX_SPEED: 7,

  RESPAWN_Y: -100,
};